name: SQ3
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2,7 * * *'
jobs:
  build:
    runs-on: ubuntu-latest 
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/Banme55/SQ3.git ~/SQ3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/SQ3
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json

      - name: '【SQ3】'
        run: |
          cd ~/SQ3/Task   
          node sqxs.js
        env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
 

